// src/lib/terms.js — plain-language explanations shown in the ⓘ tooltips

export const TERMS = {
  strike:     'The price you agree to sell your shares at if the buyer uses the option.',
  expiry:     'The date the option ends. After this, you keep the premium and can sell a new one.',
  dte:        'Days left until the option expires.',
  premium:    'Cash you receive up front for selling the option, at a price you can realistically get (between the bid and the midpoint) and after your usual commission. It is yours to keep.',
  keep:       'The premium minus the buyback reserve and your usual commission.',
  fed:        'Expires after a Federal Reserve rate decision, which can move the whole market.',
  industry:   'Expires after earnings from big companies in the same industry (or your other stocks in it), which often move the whole group.',
  fillPrice:  'What you can expect per share when selling: the midpoint between the bid and the ask, where sell orders usually fill. Before commission.',
  yield:      'What you keep after commission, as a yearly return on your shares, so options with different lengths can be compared.',
  upside:     'How much the stock can rise before it reaches the strike and your shares may be sold.',
  delta:      'Delta, shown as a rough chance the stock ends above the strike and your shares get called away.',
  spread:     'Gap between the buy and sell quote. Smaller means a fairer, easier fill.',
  quote:      'Current: today\'s quote, about 15 minutes behind. Closing: the last session\'s closing quote (market closed, or just opened). Last trade: no closing quote, so the last price it traded at. Old price: last traded before the latest session, so the picks skip it.',
  closingQuote: "The midpoint of this option's bid and ask at the last session's close. Good for planning; today's price can differ once trading moves.",
  lastTrade:  "No closing quote, so this is the last price the option traded at. It can be out of date if it hasn't traded for a while.",
  oldPrice:   "This option hasn't traded since before the latest session, so its price is from when the stock was elsewhere. The picks skip it.",
  income:     'Income trades aim for the highest premium, with strikes closer to today’s price.',
  balanced:   'Balanced trades leave more room for the stock to rise, for a smaller premium. The pick aims for about a 12% chance of being called.',
  available:  'Contracts you can still sell. Each contract covers 100 shares.',
  buyback:    'Money set aside to buy the option back early if it becomes cheap.',
  profit:     'How much of the original premium you have kept so far. Buying back near the target locks in the gain.',
  buybackPrice: 'Your buy-back target as a price per share. Options trade in whole cents, so it is the closest cent to your target, which can keep slightly more or less than the target. Set it as a limit order with your broker.',
  minStrike:  'Optional: only show strikes at least this far above today’s price, e.g. 5% on a $100 stock means strikes of $105 or more. Leave at 0 to rely on your chance-of-being-called range (Strategy page).',
  minPremium: 'Ignore options paying less than this per share.',
  volume:     'Minimum contracts traded today. Higher means easier to trade.',
  openInt:    'Minimum open contracts. Higher means a more active, reliable market.',
  belowCost:  'The strike is under what you paid per share. If the shares are called away you sell them for less than you paid (the premium covers only part of that).',
  earnings:   'The company reports earnings before this option expires. The stock can jump on the news, which raises the chance your shares are called away.',
  exDividend: 'The stock goes ex-dividend before this option expires. If it is above the strike, the buyer may exercise early to collect the dividend.',
  net:        'Premium collected minus what you paid to buy it back and any fees. Gains or losses on shares that were called away are on the Performance page.',
  buyToClose: 'What your broker calls buying back a call you sold. Pick "buy to close", not "buy to open", so the order ends your call instead of opening a new one.',
  fill:       "The price your broker actually sold each option for, from the order confirmation. If it matched the quote, \"Use these\" fills the quotes in.",
}
